// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"classroom-analysis/internal/ioc"
	"classroom-analysis/internal/mq"
	"classroom-analysis/internal/repository"
	"classroom-analysis/internal/repository/dao"
	"classroom-analysis/internal/service"
	"classroom-analysis/internal/web"
	"classroom-analysis/internal/ws"

	_ "classroom-analysis/docs"
)

// Injectors from wire.go:

func InitWebServer() *App {
	client := ioc.InitMongodb()
	v := ioc.InitLogger(client)
	database := ioc.InitMongoDatabase(client)
	patientDAO := dao.NewPatientDAO(database)
	patientRepository := repository.NewPatientRepository(patientDAO)
	patientService := service.NewPatientService(patientRepository)
	patientHandler := web.NewPatientHandler(patientService)
	minioClient := ioc.NewMinioClient()
	fileDao := dao.NewFileDao(database)
	fileDaoInterface := dao.ProvideFileDaoInterface(fileDao)
	fileRepository := repository.NewFileRepository(fileDaoInterface)
	fileInterface := repository.ProvideFileInterface(fileRepository)
	fileServiceInterface := service.NewFileService(minioClient, fileInterface)
	fileHandler := web.NewFileHandler(fileServiceInterface)
	userDAO := dao.NewUserDAO(database)
	userRepository := repository.NewUserRepository(userDAO)
	userService := service.NewUserService(userRepository)
	userHandler := web.NewUserHandler(userService)
	healthManagerDAO := dao.NewHealthManagerDAO(database)
	healthManagerRepository := repository.NewHealthManagerRepository(healthManagerDAO)
	healthManagerService := service.NewHealthManagerService(healthManagerRepository)
	healthManagerHandler := web.NewHealthManagerHandler(healthManagerService)
	roomDAO := dao.NewRoomDAO(database)
	roomRepository := repository.NewRoomRepository(roomDAO)
	roomService := service.NewRoomService(roomRepository)
	roomHandler := web.NewRoomHandler(roomService)
	bedDAO := dao.NewBedDAO(database)
	bedRepository := repository.NewBedRepository(bedDAO)
	customerDAO := dao.NewCustomerDAO(database)
	customerRepository := repository.NewCustomerRepository(customerDAO)
	bedService := service.NewBedService(bedRepository, roomRepository, customerRepository)
	bedHandler := web.NewBedHandler(bedService)
	careLevelDAO := dao.NewCareLevelDAO(database)
	careLevelRepository := repository.NewCareLevelRepository(careLevelDAO)
	careLevelService := service.NewCareLevelService(careLevelRepository)
	careLevelHandler := web.NewCareLevelHandler(careLevelService)
	dietPlanDAO := dao.NewDietPlanDAO(database)
	dietPlanRepository := repository.NewDietPlanRepository(dietPlanDAO)
	dietPlanService := service.NewDietPlanService(dietPlanRepository)
	dietPlanHandler := web.NewDietPlanHandler(dietPlanService)
	customerService := service.NewCustomerService(customerRepository, userRepository, bedRepository, careLevelRepository, dietPlanRepository)
	customerHandler := web.NewCustomerHandler(customerService)
	recordDAO := dao.NewRecordDAO(database)
	recordRepository := repository.NewRecordRepository(recordDAO)
	recordService := service.NewRecordService(recordRepository, customerRepository, bedRepository, careLevelRepository)
	recordHandler := web.NewRecordHandler(recordService)
	serviceDAO := dao.NewServiceDAO(database)
	serviceRepository := repository.NewServiceRepository(serviceDAO)
	customerServiceDAO := dao.NewCustomerServiceDAO(database)
	customerServiceRepository := repository.NewCustomerServiceRepository(customerServiceDAO)
	serverService := service.NewServiceService(serviceRepository, customerServiceRepository, customerRepository)
	serviceHandler := web.NewServiceHandler(serverService)
	careRecordDAO := dao.NewCareRecordDAO(database)
	careRecordRepository := repository.NewCareRecordRepository(careRecordDAO)
	careRecordService := service.NewCareRecordService(careRecordRepository)
	careRecordHandler := web.NewCareRecordHandler(careRecordService)
	webSocketManager := ws.NewWebSocketManager()
	analysisDAO := dao.NewAnalysisDAO(database)
	analysisRepository := repository.NewAnalysisRepository(analysisDAO)
	analysisService := service.NewAnalysisService(analysisRepository)
	analysisHandler := web.NewAnalysisHandler(analysisService)
	statsService := service.NewStatsService()
	statsHandler := web.NewStatsHandler(statsService)
	alertHandler := web.NewAlertHandler(analysisService)
	notificationHandler := web.NewNotificationHandler()
	compatHandler := web.NewCompatHandler(customerService, statsService)
	engine := ioc.InitGin(v, patientHandler, fileHandler, userHandler, healthManagerHandler, roomHandler, bedHandler, careLevelHandler, dietPlanHandler, customerHandler, recordHandler, serviceHandler, careRecordHandler, webSocketManager, analysisHandler, statsHandler, alertHandler, notificationHandler, compatHandler)
	redisClient := ioc.InitRedis()
	config := ioc.InitViper()
	alertConsumer := mq.NewAlertConsumer()
	alertService := service.NewAlertService(alertConsumer, webSocketManager, analysisService)
	app := &App{
		server:       engine,
		mongodb:      client,
		redis:        redisClient,
		minio:        minioClient,
		config:       config,
		FileHandler:  fileHandler,
		AlertService: alertService,
	}
	return app
}
