// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"classroom-analysis/internal/ioc"
	"classroom-analysis/internal/repository"
	"classroom-analysis/internal/repository/dao"
	"classroom-analysis/internal/service"
	"classroom-analysis/internal/web"
)

import (
	_ "classroom-analysis/docs"
)

// Injectors from wire.go:

func InitWebServer() *App {
	client := ioc.InitMongodb()
	v := ioc.InitLogger(client)
	database := ioc.InitMongoDatabase(client)
	patientDAO := dao.NewPatientDAO(database)
	patientRepository := repository.NewPatientRepository(patientDAO)
	patientService := service.NewPatientService(patientRepository)
	patientHandler := web.NewPatientHandler(patientService)
	minioClient := ioc.NewMinioClient()
	fileDao := dao.NewFileDao(database)
	fileDaoInterface := dao.ProvideFileDaoInterface(fileDao)
	fileRepository := repository.NewFileRepository(fileDaoInterface)
	fileInterface := repository.ProvideFileInterface(fileRepository)
	fileServiceInterface := service.NewFileService(minioClient, fileInterface)
	fileHandler := web.NewFileHandler(fileServiceInterface)
	userDAO := dao.NewUserDAO(database)
	userRepository := repository.NewUserRepository(userDAO)
	userService := service.NewUserService(userRepository)
	userHandler := web.NewUserHandler(userService)
	healthManagerDAO := dao.NewHealthManagerDAO(database)
	healthManagerRepository := repository.NewHealthManagerRepository(healthManagerDAO)
	healthManagerService := service.NewHealthManagerService(healthManagerRepository)
	healthManagerHandler := web.NewHealthManagerHandler(healthManagerService)
	roomDAO := dao.NewRoomDAO(database)
	roomRepository := repository.NewRoomRepository(roomDAO)
	roomService := service.NewRoomService(roomRepository)
	roomHandler := web.NewRoomHandler(roomService)
	bedDAO := dao.NewBedDAO(database)
	bedRepository := repository.NewBedRepository(bedDAO)
	bedService := service.NewBedService(bedRepository, roomRepository)
	bedHandler := web.NewBedHandler(bedService)
	careLevelDAO := dao.NewCareLevelDAO(database)
	careLevelRepository := repository.NewCareLevelRepository(careLevelDAO)
	careLevelService := service.NewCareLevelService(careLevelRepository)
	careLevelHandler := web.NewCareLevelHandler(careLevelService)
	dietPlanDAO := dao.NewDietPlanDAO(database)
	dietPlanRepository := repository.NewDietPlanRepository(dietPlanDAO)
	dietPlanService := service.NewDietPlanService(dietPlanRepository)
	dietPlanHandler := web.NewDietPlanHandler(dietPlanService)
	customerDAO := dao.NewCustomerDAO(database)
	customerRepository := repository.NewCustomerRepository(customerDAO)
	customerService := service.NewCustomerService(customerRepository, userRepository, bedRepository)
	customerHandler := web.NewCustomerHandler(customerService)
	recordDAO := dao.NewRecordDAO(database)
	recordRepository := repository.NewRecordRepository(recordDAO)
	recordService := service.NewRecordService(recordRepository, customerRepository, bedRepository)
	recordHandler := web.NewRecordHandler(recordService)
	serviceDAO := dao.NewServiceDAO(database)
	serviceRepository := repository.NewServiceRepository(serviceDAO)
	customerServiceDAO := dao.NewCustomerServiceDAO(database)
	customerServiceRepository := repository.NewCustomerServiceRepository(customerServiceDAO)
	serviceService := service.NewServiceService(serviceRepository, customerServiceRepository, customerRepository)
	serviceHandler := web.NewServiceHandler(serviceService)
	engine := ioc.InitGin(v, patientHandler, fileHandler, userHandler, healthManagerHandler, roomHandler, bedHandler, careLevelHandler, dietPlanHandler, customerHandler, recordHandler, serviceHandler)
	redisClient := ioc.InitRedis()
	config := ioc.InitViper()
	app := &App{
		server:      engine,
		mongodb:     client,
		redis:       redisClient,
		minio:       minioClient,
		config:      config,
		FileHandler: fileHandler,
	}
	return app
}
