// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"classroom-analysis/internal/ioc"
	"classroom-analysis/internal/repository"
	"classroom-analysis/internal/repository/dao"
	"classroom-analysis/internal/service"
	"classroom-analysis/internal/web"
)

// Injectors from wire.go:

func InitWebServer() *App {
	client := ioc.InitMongodb()
	v := ioc.InitLogger(client)
	database := ioc.InitMongoDatabase(client)
	patientDAO := dao.NewPatientDAO(database)
	patientRepository := repository.NewPatientRepository(patientDAO)
	patientService := service.NewPatientService(patientRepository)
	patientHandler := web.NewPatientHandler(patientService)
	minioClient := ioc.NewMinioClient()
	fileDao := dao.NewFileDao(database)
	fileDaoInterface := dao.ProvideFileDaoInterface(fileDao)
	fileRepository := repository.NewFileRepository(fileDaoInterface)
	fileInterface := repository.ProvideFileInterface(fileRepository)
	fileServiceInterface := service.NewFileService(minioClient, fileInterface)
	fileHandler := web.NewFileHandler(fileServiceInterface)
	engine := ioc.InitGin(v, patientHandler, fileHandler)
	redisClient := ioc.InitRedis()
	config := ioc.InitViper()
	app := &App{
		server:      engine,
		mongodb:     client,
		redis:       redisClient,
		minio:       minioClient,
		config:      config,
		FileHandler: fileHandler,
	}
	return app
}
